# 基本配置
name = "cursdocs"
compatibility_date = "2024-01-04"

# 建置配置
[build]
command = "pnpm run build"
# 指定要上傳的檔案和目錄
upload.format = "directory"
upload.dir = "out"
# 排除快取目錄
exclude = [".next/cache/**"]

# 環境變數配置
[build.environment]
NODE_VERSION = "18.18.0"

# Pages 配置
[pages]
# 指定根目錄
directory = "out"